name: Build and verify finance app

env:
  BUILD_PROFILE: ci

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build-workflow.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build-workflow.yaml'

jobs:
  project-build:
    runs-on: ubuntu-latest
    container: node:20-bullseye
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: finance
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Gradle Build
        run: ./scripts/build.sh